mkdir "camera shake"
mkdir "cause type"
mkdir "clone"
mkdir "difficulty"
mkdir "fill"
mkdir "gamemodes"
mkdir "handtype"
mkdir "locate feature"
mkdir "mask"
mkdir "mirror"
mkdir "music repeat"
mkdir "old block"
mkdir "operation"
mkdir "replace"
mkdir "ride fill"
mkdir "ride rules"
mkdir "rotation"
mkdir "save"
mkdir "selector attribute"
mkdir "selector type"
mkdir "slot type"
mkdir "structure animation"
mkdir "teleport rules"
mkdir "time"

echo "# Mode - camera shake - Invalid" >> "camera shake/invalid.md"
echo "# Mode - cause type - Invalid" >> "cause type/invalid.md"
echo "# Mode - clone - Invalid" >> "clone/invalid.md"
echo "# Mode - difficulty - Invalid" >> "difficulty/invalid.md"
echo "# Mode - fill - Invalid" >> "fill/invalid.md"
echo "# Mode - gamemodes - Invalid" >> "gamemodes/invalid.md"
echo "# Mode - handtype - Invalid" >> "handtype/invalid.md"
echo "# Mode - locate feature - Invalid" >> "locate feature/invalid.md"
echo "# Mode - mask - Invalid" >> "mask/invalid.md"
echo "# Mode - mirror - Invalid" >> "mirror/invalid.md"
echo "# Mode - music repeat - Invalid" >> "music repeat/invalid.md"
echo "# Mode - old block - Invalid" >> "old block/invalid.md"
echo "# Mode - operation - Invalid" >> "operation/invalid.md"
echo "# Mode - replace - Invalid" >> "replace/invalid.md"
echo "# Mode - ride fill - Invalid" >> "ride fill/invalid.md"
echo "# Mode - ride rules - Invalid" >> "ride rules/invalid.md"
echo "# Mode - rotation - Invalid" >> "rotation/invalid.md"
echo "# Mode - save - Invalid" >> "save/invalid.md"
echo "# Mode - selector attribute - Invalid" >> "selector attribute/invalid.md"
echo "# Mode - selector type - Invalid" >> "selector type/invalid.md"
echo "# Mode - slot type - Invalid" >> "slot type/invalid.md"
echo "# Mode - structure animation - Invalid" >> "structure animation/invalid.md"
echo "# Mode - teleport rules - Invalid" >> "teleport rules/invalid.md"
echo "# Mode - time - Invalid" >> "time/invalid.md"